### ISSUE TITLE
Failing to end a transaction in a batch yields no error or warning

### ISSUE THREAD

**Issue by CodingDoug** [libsql/sqld#411]
Consider the following JSON payload:

```json
{
  "batch": {
    "steps": [
      {
        "stmt": {
          "sql": "begin"
        }
      },
      {
        "stmt": {
          "sql": "delete ..."
        }
      }
    ]
  }
}
```

When sent to /v1/batch, it will yield no errors, yet also not actually commit the delete because there was no "end" statement.  Adding "end" commits the delete.

I'm not sure about the best way to handle this, but every begin-type statement *that is actually executed (and not skipped because of a condition)* should be paired with an end-type statement. If the batch ends with an active transaction, then the caller needs to see an error to that effect.

@honzasp

**Comment by honzasp** [comment]
This is actually intended behavior. Hrana is by design oblivious to the content of the SQL statements and to transaction boundaries, so you can execute arbitrary statements in the `batch` request, it is not tied to transactions in any way.

In the case of the `/v1/batch` endpoint, each request is executed on a separate logical database connection which is closed after the request, so if you begin a transaction and don't commit, it will be automatically rolled back.

**Comment by CodingDoug** [comment]
The problem here is that the results are confusing given the expectations of the caller.  If we can tell that there is something they *might* be doing wrong, given how we expect the API to be used, it's good DX to surface that (like lint).  I can think of no actual use case where someone would legitimately want to use begin without end. I'd suggest introducing a new top-level result for warnings or other informational message that would help someone diagnose the problem.

**Comment by honzasp** [comment]
One place that will use BEGIN without COMMIT/ROLLBACK in a batch is libsql client. When you write

```
const txn = await client.transaction();
const rs = await txn.execute("DELETE FROM t");
```

then the client should send both "BEGIN" and "DELETE" in a single batch, to ensure that the `DELETE` is executed only if the `BEGIN` succeeded. Right now, libsql client sends an execute request with the BEGIN and waits for it to complete before sending the "DELETE", but this introduces an unnecessary network roundtrip.

The batch request was added as a general mechanism to reduce latency by doing rudimentary conditional execution on the server. It is by design quite general, to handle even unanticipated use cases, such as the optimization that I described here.

**Comment by CodingDoug** [comment]
The transaction example doesn't use /v1/batch though, does it?  It's multiple round trips, not a single request.  I'm talking exclusively about a single request batch that fails to end the transaction it started, all within the scope of that one request.

**Comment by honzasp** [comment]
The transaction example uses (or, rather, will use) the `batch` request on WebSocket or with HTTP API v2. The `/v1/batch` endpoint in HTTP API v1 uses exactly the same semantics as the `batch` request, that's why it may not make sense. However, the v1 API will soon be deprecated by v2.
