### ISSUE TITLE
Error message a bit confusing when request JSON values are not the expected type

### ISSUE THREAD

**Issue by CodingDoug** [libsql/sqld#412]
With the following named argument to a SQL query:

```json
{
  "name": ":level",
  "value": {
    "type": "integer",
    "value": "1"
  }
},
```

The error returned to the client is:

> Could not parse request body: invalid type: integer `1`, expected a borrowed string at line 1 column 330

It's possible to read this and understand what to do, but the word "borrowed" here is not intuitive for the caller. It looks like it's unnecessarily exposing some Rust implementation details. Ideally error messages are actionable for the caller considering that they're consuming an API/protocol and not writing Rust.

Other related confusing messages:

> Could not parse request body: invalid type: sequence, expected a borrowed string at line 1 column 331

(when providing an array instead of a string; "sequence" is not correct terminology)

> Could not parse request body: invalid type: map, expected a borrowed string at line 1 column 331

(when providing an object, "map" is not correct terminology)

As much as possible, let's use JSON terminology to construct an error message that's meaningful to the caller.

@honzasp

**Comment by honzasp** [comment]
The first error message is weird: you did pass `"value": "1"`, this should be correct. Maybe you passed `"value": 1` (i.e., integer instead of string)?

Unfortunately, these error messages are generated by serde, the Rust library that we are using for deserialization, so we can't control the precise wording. I agree that the messages could be improved to use JSON-specific terminology instead of generic serde terminology ("arrays" instead of "sequences"), but fixing this would require deserializing the JSONs by hand instead of using serde.
