### ISSUE TITLE
Make replication requests count as idle kick

### ISSUE THREAD

**Issue by penberg** [libsql/sqld#506]
We currently only consider client requests as "idle kick" that defers scale to zero. However, a primary should also consider replication frame requests as "idle kick"; otherwise you might have a very active primary (that only serves replication requests) that scales to zero.

**Comment by haaawk** [comment]
I might be mistaken but I remember that replica frame request is also an "idle kick". @MarinPostma [implemented it long time ago](https://github.com/libsql/sqld/commit/84ac150b538e2c59ddb018aa2bbaaca76552f8a6#diff-830b94ec82342e333125aeade9ead9990e8810142778d07fc7122378976e91e7L46) I believe and it's still present in [the code](https://github.com/libsql/sqld/blob/main/sqld/src/rpc/mod.rs#L52).

The only situation I can imagine when replica is up but primary is not is when all replicas and primary were scaled to zero and then a new request was routed to the replica and woke it up. I'm not sure if replicas are able to wake up the primary or they can only keep it awake.

FYI @penberg @athoscouto because I believe you've observed the behaviour

**Comment by haaawk** [comment]
I think I know what the issue is. 
It seems that we're using long polling when fetching new frames.
Each fetch does the "idle kick" but if there are no new frames - the request will wait until new frames appear.
While hanging, the replica won't send another frames fetch until the previous one is done.
If there are no new changes happening for long enough, the replica won't send any new requests to fetch the frames.
Some code pointers -> https://github.com/libsql/sqld/blob/main/sqld/src/replication/primary/frame_stream.rs#L87
When can replica outlive the primary:
`When there are reads happening on replica and keeping it alive but no writes happening to keep primary alive. Since there are no writes, the replication will hang`

**Comment by haaawk** [comment]
Here's a fix https://github.com/libsql/sqld/pull/517
