### ISSUE TITLE
Compact Hrana encoding

### ISSUE THREAD

**Issue by honzasp** [libsql/sqld#543]
The JSON encoding in Hrana is quite verbose, which might be a problem for large result sets. This is not a big issue right now, because [we don't support large result sets anyway](https://github.com/libsql/sqld/issues/542), but once we fix this, we might want to make the encoding more compact.

There are at least three options, ordered from easier and less efficient to harder and more efficient:

1. Compress the JSON encoding. There are two suboptions:
    1. Use compression on the transport protocol: HTTP supports compression natively, and WebSockets support it with an extension. Compression support for HTTP clients should be very good, but some of the WebSocket client implementations that we rely on might not support compression.
    2. Use compression at a higher level: this doesn't make much sense for HTTP, but might be necessary for WebSockets.
2. Use an existing binary encoding, such as Protobufs.
3. Use a specialized binary encoding.

**Comment by barbieri** [comment]
you can use also shorter keys (just like JWT, 1-3 letters will be enough) and also move the type wrapping out of each cell. 

While I get why it's like that, SQLite itself allows you to read different types and we could replicate that... like send the decltype in the column (already done), send the sqlite3_column_type() in there as well. Then for each row, send the safest + most compact json encoding for it. Ex:

- strings: send as strings
- int up to 32 bits: send as number (are 64 safe everywhere?)
- float send as number
- boolean send as boolean
- blob you can send as string as base64. In order to differentiate from string, you may return as an array with string inside it, the overhead is low (2 bytes), decoding is simple as arrays are handled as first-class citizen in parsing

Then a row composed of int, string, bool and blob could be as short as:

```json
[1,2,3.14,"hello",["eHB0bwo="],true,false]
```

which is reasonable compared to what is being sent now.

**Comment by MarinPostma** [comment]
@honzasp can we close this?
